using System.Net;
using System.Net.Mail;

namespace MindShield.Web.Services
{
    public class EmailGuardianService : IGuardianNotificationService
    {
        private readonly IConfiguration _config;

        public EmailGuardianService(IConfiguration config)
        {
            _config = config;
        }

        public async Task SendAlertAsync(string guardianName, string guardianEmail, string riskReason, string originalText)
        {
            try
            {
                // Pull these from dotnet user-secrets
                var senderEmail = _config["Email:Sender"];
                var senderPassword = _config["Email:AppPassword"];

                using var client = new SmtpClient("smtp.gmail.com", 587)
                {
                    Credentials = new NetworkCredential(senderEmail, senderPassword),
                    EnableSsl = true
                };

                var mailMessage = new MailMessage
                {
                    From = new MailAddress(senderEmail, "MindShield Guardian"),
                    Subject = "🚨 URGENT: MindShield Intervention Alert",
                    IsBodyHtml = true,
                    Body = $@"
                        <div style='font-family: Arial, sans-serif; padding: 20px; border: 2px solid #d9534f; border-radius: 10px; max-width: 500px;'>
                            <h2 style='color: #d9534f; margin-top: 0;'>🛡️ MindShield Intervention</h2>
                            <p>Hello {guardianName},</p>
                            <p>A severe risk social media post was just intercepted and blocked by MindShield.</p>
                            <p><strong>Flagged Reason:</strong> {riskReason}</p>
                            <hr style='border: 1px solid #eee; margin: 20px 0;'/>
                            <p style='color: #666; font-size: 0.9em;'><strong>Intercepted Draft:</strong></p>
                            <blockquote style='background: #f9f9f9; padding: 15px; border-left: 4px solid #ccc; font-style: italic; margin: 0;'>
                                ""{originalText}""
                            </blockquote>
                            <br/>
                            <p><strong>Please reach out to check in.</strong></p>
                            <small style='color: #aaa;'>Automated alert generated by MindShield AI.</small>
                        </div>"
                };

                mailMessage.To.Add(guardianEmail);

                await client.SendMailAsync(mailMessage);
                Console.WriteLine($"[GUARDIAN ALERT] Email fired off successfully to {guardianEmail}.");
            }
            catch (Exception ex)
            {
                // Failsafe so the demo UI doesn't crash if the email bounces
                Console.WriteLine($"[GUARDIAN ALERT FAILED] {ex.Message}");
            }
        }
    }
}